### PR TITLE
Save uploaded file to Channel Entry

### PR DESCRIPTION
**Pull request by tobz-nz**
This pull request saves the location returned by S3 as the value of the field so you can use the uploaded file in your templates.

### CODE REVIEW

**Comment by khaliqgant** [comment]
Super sorry for the delay! I never received a notification about this. Will review and respond ASAP

**Comment by khaliqgant** [comment]
Thanks again. I think this is a great idea. Ran into a small issue and had a couple of questions. I tested on version 2.7.2 and from checking our your PR received the following error  when trying to use the field

```
Fatal error: Call to undefined function get_mime_by_extension()
```

Screenshot: http://cl.ly/image/0S1h3P3S3M0a

I fixed by loading in the EE file helper in the constructor

```
$this->EE->load->helper('file');
```

What version of EE did you use when trying this out?

1) I'm unsure in the Javascript what fieldId refers to, I get an undefined value when logging it?

```
var fieldId = $form.attr('data-field-id')
```

2) Are you loading in additional fields somewhere? Specifically, I'm referring to this line

```
$('.vmg-filename a', $form).attr('href', fileLocation).text(fileLocation);
```

Would love to get this functionality in, so let me know if you could clarify these things!

**Comment by tobz-nz** [comment]
Hi,

I did this on EE 2.9.1 I think.

I actually made some more significant changes but haven’t pushed them up to my fork yet, so maybe hold off on this pull request for now.

I can’t remember off the top of my head how I did things.. I think I was generating a hidden field for each file uploaded.. or concating the filenames together or something.. I really can’t remember.

I’m on another project at the moment so it might be a while until I can get back & finish it.

I will update the pull request when I can.

Cheers,

Toby

—

**Comment by khaliqgant** [comment]
Gotcha, no worries. Look forward to the updated PR when you get around to it. Going to close this original PR in the mean time.

**Pull request closed without merging**
